docs: move default props to Dropzone component for react-docgen
react-dropzone/react-dropzone pull request #1015
Opened 2020-10-05 16:09 UTC by samuelfullerthomas

**What kind of change does this PR introduce?**

- [ ] bugfix
- [ ] feature
- [ ] refactoring / style
- [ ] build / chore
- [x] documentation

**Did you add tests for your changes?**

- [x] Not relevant

**If relevant, did you update the documentation?**

- [x] Yes, I've updated the documentation

**Summary**

Hello! This PR simply moves the default props from the hook to the defaultProps property on the Dropzone component, so that the defaults can be documented on the documentation site.

### Current
![current](https://user-images.githubusercontent.com/10165959/95104100-5a02fc80-072d-11eb-9225-c7930d5cecaa.png)

### With default props
![with-pr](https://user-images.githubusercontent.com/10165959/95104088-57a0a280-072d-11eb-842c-9716cdea35f5.png)

**Does this PR introduce a breaking change?**

No!
**Other information**

2020-10-13 16:55 UTC, samuelfullerthomas commented
Any thoughts on this @rolandjitsu ?

2020-10-14 01:57 UTC, rolandjitsu requested changes

2020-10-14 01:57 UTC, rolandjitsu commented on src/index.js
> +const DefaultProps = {
```suggestion
const defaultProps = {
```

2020-10-14 13:27 UTC, rolandjitsu approved these changes

2020-10-14 13:27 UTC, merged