fix: Improve accessibility of input
react-dropzone/react-dropzone pull request #1219
Opened 2022-07-30 01:19 UTC by vbudovski

Using "display: none" often prevents screen readers from seeing the content. What we really want is to visually hide
the standard input. We also add a placeholder to be announced by screen readers which can optionally be rendered also.

**What kind of change does this PR introduce?**
- [x] Bug Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Style
- [ ] Build
- [ ] Chore
- [ ] Documentation
- [ ] CI

**Did you add tests for your changes?**
- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**
- [x] Yes, I've updated the documentation
- [ ] Not relevant

**Summary**
Using "display: none" often prevents screen readers from seeing the content. What we really want is to visually hide
the standard input. We also add a placeholder to be announced by screen readers which can optionally be rendered also.

**Does this PR introduce a breaking change?**
Non-breaking change.

**Other information**

2022-09-12 06:06 UTC, brandonpittman commented
What's the blocker on this?

2024-10-02 12:37 UTC, rolandjitsu requested changes

2024-10-02 12:37 UTC, rolandjitsu commented on src/index.js
> +          'aria-placeholder': placeholder,
This is a property that you can set with `getInputProps({'aria-placeholder': 'drop files'})`. Let's limit this change to just the style change.

2024-10-26 18:29 UTC, rolandjitsu commented
@vbudovski let me know if you'd still like to push this through and make the requested changes.

2024-11-03 11:27 UTC, rolandjitsu commented
Closing in favour of https://github.com/react-dropzone/react-dropzone/pull/1395.

2024-11-03 11:27 UTC, closed without merging