feat: add human-readable file size formatting to error messages
react-dropzone/react-dropzone pull request #1321
Opened 2023-10-10 00:50 UTC by issambaccouch

**What kind of change does this PR introduce?**
- [ ] Bug Fix
- [x] Feature
- [ ] Refactoring
- [ ] Style
- [ ] Build
- [ ] Chore
- [ ] Documentation
- [ ] CI

**Did you add tests for your changes?**
- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**
- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**
This pull request addresses the need for user-friendly error messages

**Does this PR introduce a breaking change?**
No
**Other information**

2024-07-17 03:00 UTC, brendonco approved these changes
Working as expected.

2024-10-02 15:49 UTC, rolandjitsu requested changes

2024-10-26 18:33 UTC, rolandjitsu commented
@issambaccouch let me know if you can make the requested changes. Also note there's https://github.com/react-dropzone/react-dropzone/pull/1304 which is related to your change.

2026-07-18 07:30 UTC, rolandjitsu commented
Addressed in https://github.com/react-dropzone/react-dropzone/pull/1475.

2026-07-18 07:30 UTC, closed without merging